/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ClassTestArray;
import javax.swing.*;

public class App {
    

    public static void main(String[] args) {
        String[] valueArray = new String[20];
        String value;
        
       
        
      for(int i = 0;i<valueArray.length;i++){
          value = JOptionPane.showInputDialog(null,"Enter Marks For Student " + (i + 1));
            
         valueArray[i] = value;
        }
      
        JOptionPane.showMessageDialog(null, valueArray);
        
        
    }        

}
