/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ClassTestArray;
import javax.swing.*;

public class App {
    

    public static void main(String[] args) {
        String[] valueArray = new String[4];
        String value;
        StringBuilder result = new StringBuilder("");
        
       
        
      for(int i = 0;i<valueArray.length;i++){
          value = JOptionPane.showInputDialog(null,"Enter Your Values " + (i + 1));
            
         valueArray[i] = value;
        }
      
        for(int i = 0;i < valueArray.length;i++){
        result.append(i+1).append(": ").append(valueArray[i]).append("\n");
        }
        JOptionPane.showMessageDialog(null,result.toString());
        
        
    }        

}
